---
title: "covid-19-analysis"
author: "Rujvi Doppalapudi"
date: "2023-07-18"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

library(tidyverse)

# Replace "path/to/covid_19_data.csv" with the actual path to the CSV file
covid_data <- read_csv("covid_19_data.csv")

# Convert the ObservationDate column to a date object
covid_data$ObservationDate <- as.Date(covid_data$ObservationDate, format = "%m/%d/%Y")


# Summarize the data by country/region and calculate the total cases, deaths, and recovered
country_data <- covid_data %>%
  group_by(`Country/Region`) %>%
  summarise(TotalCases = sum(Confirmed),
            TotalDeaths = sum(Deaths),
            TotalRecovered = sum(Recovered)) %>%
  arrange(desc(TotalCases))

# Bar plot for total cases, deaths, and recovered
ggplot(country_data, aes(x = reorder(`Country/Region`, TotalCases), y = TotalCases, fill = "Total Cases")) +
  geom_bar(stat = "identity") + scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
  labs(title = "Total COVID-19 Cases by Country/Region",
       x = "Country/Region",
       y = "Total Cases")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(country_data, aes(x = reorder(`Country/Region`, TotalDeaths), y = TotalDeaths, fill = "Total Deaths")) +
  geom_bar(stat = "identity") +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
  labs(title = "Total COVID-19 Deaths by Country/Region",
       x = "Country/Region",
       y = "Total Deaths") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(country_data, aes(x = reorder(`Country/Region`, TotalRecovered), y = TotalRecovered, fill = "Total Recovered")) +
  geom_bar(stat = "identity") +
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE)) +
  labs(title = "Total COVID-19 Recovered Cases by Country/Region",
       x = "Country/Region",
       y = "Total Recovered") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
